services:
  php:
    build:
      context: ./back
    container_name: gamodoo_php
    volumes:
      - ./back:/var/www/html
    working_dir: /var/www/html
    environment:
      APP_ENV: dev
      DATABASE_URL: sqlite:///%kernel.project_dir%/var/app.db
      CORS_ALLOW_ORIGIN: ^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$
      JWT_SECRET_KEY: /var/www/html/config/jwt/private.pem
      JWT_PUBLIC_KEY: /var/www/html/config/jwt/public.pem
      JWT_PASSPHRASE: gamodoo_jwt_passphrase

  nginx:
    image: nginx:alpine
    container_name: gamodoo_nginx
    ports:
      - "8080:80"
    volumes:
      - ./back:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  frontend:
    build:
      context: ./front
    container_name: gamodoo_nextjs
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
    command: npm run dev
